version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Docker/development/Dockerfile
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mongo:3.4
    ports:
      - "27018:27017"
